Add WebLayout User Property
matrix-org/matrix-analytics-events pull request #75
Opened 2022-10-21 15:26 UTC by t3chguy

2022-10-24 07:57 UTC, t3chguy commented on schemas/UserProperties.json
> +        ]
Because mobile doesn't have IRC & Compact, and if Compact were added it may behave differently (may apply to bubble layout too for example)

2022-10-24 08:00 UTC, bmarty commented on schemas/UserProperties.json
> +        ]
I do not see the pb if mobile apps use only the 2 of the 4 values. Will it lead to wrong result during analysis?
I also though about `TimelineLayout`, but I was not sure if it impacted the room list as well.

2022-10-24 08:33 UTC, t3chguy commented on schemas/UserProperties.json
> +        ]
Sure but then it means that if Mobile ever implements a Compact mode it must apply only to the default layout and *not* to bubble layout which may be restrictive.

2022-10-24 09:17 UTC, bmarty commented on schemas/UserProperties.json
> +        ]
Ok

2022-10-26 11:51 UTC, daniellekirkwood approved these changes
Discussed in Analytics internal [here](https://matrix.to/#/!GxLiIEjsFmjwFqumva:matrix.org/$VMtsKORr1gc1MhKdWzazVh5vQ_d7XXFR7o2GV89IQvo?via=matrix.org&via=element.io&via=one.ems.host)

there are different ways of doing this event but as we want to keep historic data, users can have different settings on different platforms, and we only want to know one-point-in-time who has what setting - this will work for now.

2022-11-03 11:10 UTC, ismailgulek requested changes
I agree with @bmarty that we should be generating the files in the PR, otherwise lgtm.

2022-11-03 11:19 UTC, ismailgulek approved these changes

2022-11-03 11:39 UTC, ismailgulek approved these changes

2022-11-03 11:49 UTC, ismailgulek approved these changes

2022-11-03 11:50 UTC, merged